[project]
name = "numerai-tabnet"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "torch",
    "pandas",
    "scikit-learn",
    "pyarrow",
    "numerapi"
]

[project.optional-dependencies]
dev = [
    "black"
]

[tool.black]
line-length = 88
target-version = ["py311"]